config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }

  resources :soups do
    get :rules, on: :collection
    get :online_counts, on: :collection
  end
  resources :clues, only: :create

  get 'my_soups', to: 'soups#owned'
end

app/models/soup.rb
class Soup < ApplicationRecord
  include AASM

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :messages,  dependent: :destroy
  has_many :clues,     dependent: :destroy

  validates :title, :description, presence: true

  after_update_commit :broadcast_soup, if: Proc.new { |soup| soup.finished? }

  scope :desc_order, -> { order(created_at: :desc) }

  aasm column: :state do
    state :active, initial: true
    state :pending
    state :finished

    event :pause do
      transitions from: :active, to: :pending
    end

    event :finish do
      transitions from: :active, to: :finished
    end

    event :continue do
      transitions from: :pending, to: :active
    end
  end

  private

  def broadcast_soup
    SoupBroadcastJob.perform_later(self)
  end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    if params[:state] && params[:state] == "finished"
      @soups = Soup.where(state: "finished").desc_order
    else
      @soups = Soup.where(state: ["active", "pending"]).desc_order
      @connection_counter = get_connection_counter(@soups.map(&:id))
    end
  end

  def show
    @soup = Soup.includes({ messages: :user }, :clues).find_by(id: params[:id])
    @clue = Clue.new

    if current_user
      @message = current_user.messages.new
    end
  end

  def new
    @soup = current_user.soups.new
  end

  def create
    @soup = current_user.soups.new(soup_params)

    if @soup.save
      redirect_to soup_path(@soup)
    else
      render :new
    end
  end

  def edit
    @soup = current_user.soups.find(params[:id])
  end

  def update
    @soup = current_user.soups.find(params[:id])
    return if @soup.finished?

    respond_to do |format|
      if @soup.update(soup_params)
        format.html { redirect_to soup_path(@soup) }
        format.json { render json: @soup, status: :created }
      else
        format.html { render :edit }
        format.json { render json: @soup.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def rules
  end

  def owned
    @soups = current_user.soups.desc_order
  end

  def online_counts
    soup_ids = params[:soup_ids]
    @connection_counter = get_connection_counter(soup_ids)

    respond_to do |format|
      format.json { render json: @connection_counter, status: :ok }
    end
  end

  private

  def soup_params
    params.require(:soup).permit(:title, :description, :state, :result)
  end

  def get_connection_counter(soup_ids)
    soup_ids.each_with_object({}) do |id, obj|
      obj[id] = ChannelConnectionCounter.new(soup_id: id).get_counts
    end
  end
end

app/helpers/soups_helper.rb
module SoupsHelper
  def finished_soups?(state)
    state == "finished"
  end

  def render_soup_state(soup)
    soup.finished? ? "finished" : soup.pending? ? "pending" : ""
  end

  def format_description(soup)
    simple_format(strip_tags(soup.description))
  end
end

app/views/soups/_flash.html.erb
<div class="soup-flash <%= render_soup_state(@soup) %>">
  <div aria-label="close" class="close-button">&times;</div>

</div>
<div class="soup-flash <%= render_soup_state(@soup) %>">
  <div aria-label="close" class="close-button">&times;</div>
  <% unless current_user %>
    <div class="text">請先登入後才能煮湯喔！</div>
  <% end %>
  <% if @soup.finished? %>
    <div class="text">此鍋湯已完成，湯主關湯啦！</div>
  <% elsif @soup.pending? %>
    <div class="text">湯主目前不在，此鍋湯將暫停留言！</div>
  <% else %>
    <div class="text"></div>
  <% end %>
</div>

app/views/soups/_form.html.erb
<%= form_for soup do |f| %>
  <%= f.label :湯名 %><br>
  <%= f.text_field :title, required: true %><br>
  <%= f.label :前情提要 %><br>
  <%= f.text_area :description, required: true %><br>

  <%= f.submit "送出" %>
<% end %>

app/views/soups/_result_form.html.erb
<div class="change-state-panel">
  恭喜完成這鍋湯！<br>
  結束前要麻煩您填寫解答唷：）

  <%= form_for soup, url: "#" do |f| %>
    <%= f.text_area :result %><br>

    <%= f.submit "送出" %>
  <% end %>
</div>

app/views/soups/_result_panel.html.erb
<div class="result-panel">
  <div><%= simple_format(strip_tags(soup.result)) %></div>
</div>

app/views/soups/edit.html.erb
<div id="soups-edit">
  <div class="title">
    <h1>修改湯的內容</h1>
  </div>

  <div class="soup-form-wrapper">
    <span>換料囉</span>
    <%= render "form", soup: @soup %>
  </div>
</div>

app/views/soups/index.html.erb
<div id="soups-index">
  <div class="title">
    <h1><%= finished_soups?(params[:state]) ? "今天要回味哪碗湯？" : "今天要選哪碗湯？" %></h1>
  </div>

  <% @soups.each do |soup| %>
    <div class="soup-block">
      <%= link_to soup_path(soup), class: "title" do %>
        <%= strip_tags soup.title %>
      <% end %>
      <div class="description"><%= format_description(soup) %></div>
      <% unless finished_soups?(params[:state]) %>
        <div class="online-counts" data-soup-id="<%= soup.id %>">
          👥 : <span><%= @connection_counter[soup.id] %></span> 人在線
        </div>
      <% end %>
      <%= link_to soup_path(soup), class: "enter-soup" do %>
        <%= finished_soups?(params[:state]) ? "看看煮完的湯" : "加入煮湯" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/soups/new.html.erb
<div id="soups-new">
  <div class="title">
    <h1>來開鍋湯吧</h1>
  </div>

  <div class="soup-form-wrapper">
    <span>開始備料囉</span>

    <%= form_for @soup do |f| %>
      <%= f.label :湯名 %><br>
      <%= f.text_field :title, required: true %><br>
      <%= f.label :前情提要 %><br>
      <%= f.text_area :description, required: true %><br>

      <%= f.submit "送出" %>
    <% end %>
  </div>
</div>

app/views/soups/owned.html.erb
<div id="soups-owned">
  <div class="title">
    <h1>我開過的湯</h1>
  </div>

  <% if @soups.present? %>
    <% @soups.each do |soup| %>
      <div class="soup-block">
        <%= link_to soup_path(soup), class: "title" do %>
          <%= strip_tags soup.title %>
        <% end %>
        <div class="description"><%= format_description(soup) %></div>
        <% unless soup.finished? %>
          <%= link_to "修改湯內容", edit_soup_path(soup), class: "edit-soup" %>
        <% end %>
        <%= link_to soup_path(soup), class: "enter-soup" do %>
          <%= soup.finished? ? "看看煮完的湯" : "加入煮湯" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="no-owned">還沒有開過任何湯唷！</div>
  <% end %>
</div>

app/views/soups/rules.html.erb
<div id="soups-rules">
  <div class="title">
    <h1>海龜湯規則</h1>
  </div>
  <div class="participant">
    <h2>煮湯人</h2>
    <ul>
      <li>最終目的為解開該故事（海龜湯）</li>
      <li>根據開湯人給的「前情提要」開始提問</li>
      <li>可以從「有用線索」查看目前的重要線索</li>
    </ul>
  </div>
  <div class="owner">
    <h2>開湯人</h2>
    <ul>
      <li>面對煮湯人的問題，僅能回答「是 or 不是」(有 or 沒有) 或是「不重要」等的簡單回答</li>
      <li>當煮湯人講到你認為是關鍵的線索時，可以在「新增線索」的地方新增</li>
      <li>把整鍋湯煮完時，開湯人可以在「新增線索」新增故事結果</li>
      <li>最後按下「完結該湯」結束故事，結束後就無法再對該鍋湯進行修改</li>
      <li>可以點選要回覆的問題，系統會直接在輸入框顯示預設訊息</li>
    </ul>
  </div>
</div>

app/views/soups/show.html.erb
<div id="soups-show">
  <div class="title">
    <h1><%= strip_tags @soup.title %></h1>
  </div>
  <div class="info-link">
    <div>
      <% if @soup.finished? %>
        <a href="#" id="result-link" class="info">查看結果</a>|
      <% elsif current_user&.author?(@soup) && !@soup.finished? %>
        <a href="#" id="change-state-link" class="info">完結該湯</a>|
        <a href="#" id="new-clue-link" class="info">新增線索</a>|
      <% end %>
      <a href="#" id="description-link" class="info">前情提要</a>|
      <a href="#" id="clue-link" class="info">有用線索</a>
    </div>
  </div>
  <%= render "flash", soup: @soup %>
  <% if @soup.finished? %>
    <%= render "result_panel", soup: @soup %>
  <% elsif current_user&.author?(@soup) && !@soup.finished? %>
    <%= render "result_form", soup: @soup %>
    <%= render "clues/form", clue: @clue %>
  <% end %>
  <div class="description-panel">
    <div><%= format_description(@soup) %></div>
  </div>
  <div class="clue-panel" id="clues">
    <div>
      <ul>
        <% @soup.clues.each do |clue| %>
          <li><%= strip_tags clue.clue %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id="messages" data-soup-id="<%= @soup.id %>" data-soup-state="<%= @soup.state %>">
      <%= render partial: "messages/message", collection: @soup.messages,
                                              as: :message,
                                              locals: { soup: @soup } %>
  </div>

  <div class="message-form-wrapper">
    <div class="exit"><%= link_to "退出", soups_path %></div>
    <% if current_user %>
      <% if @soup.active? %>
        <%= render "messages/form", message: @message %>
      <% end %>
    <% else %>
      <div class="login-first">
        請先 <%= link_to "登入", user_session_path %> 或 <%= link_to "註冊", new_user_registration_path %>
      </div>
    <% end %>
  </div>
</div>