config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }

  resources :soups do
    get :rules, on: :collection
    get :online_counts, on: :collection
  end
  resources :clues, only: :create

  get 'my_soups', to: 'soups#owned'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @rand_soup = Soup.where(state: "active").sample
  end
end

app/views/welcome/index.html.erb
<div id="welcome">
  <section class="background">
    <div class="content-wrapper">
      <div class="header">
        <h1>
          <div class="site-logo">
            <span>海龜湯</span>
          </div>
        </h1>
      </div>
      <div class="slogan">
        <p>沒玩過 <span>海。龜。湯</span>？</p>
        <p>註冊後即可加入☺️</p>
      </div>
      <div class="random">
        <% if @rand_soup %>
          <%= link_to "隨機選湯開始玩 👈", soup_path(@rand_soup) %>
        <% else %>
          <%= link_to "看看有啥海龜湯 👈", soups_path %>
        <% end %>
      </div>
      <div class="arrows"></div>
    </div>
  </section>
  <section class="background">
    <div class="content-wrapper">
      <div class="list">
        <div class="more">
          <ul>
            <li><%= link_to "查看海龜湯規則 👈", rules_soups_path %></li>
            <li><%= link_to "我想要開個新湯 👈", new_soup_path %></li>
            <li><%= link_to "看看有啥海龜湯 👈", soups_path %></li>
            <li><%= link_to "那些已完結的湯 👈", soups_path(state: "finished") %></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</div>

<% content_for :page_specific_javascript do %>
  <%= javascript_include_tag "fsvs" %>
<% end %>