config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords'
  }

  resources :soups do
    get :rules, on: :collection
    get :online_counts, on: :collection
  end
  resources :clues, only: :create

  get 'my_soups', to: 'soups#owned'
end

app/views/layouts/_footer.html.erb
<footer>
  Copyright © 2018 Alanyeh. All rights reserved
</footer>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-81003180-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-81003180-5');
</script>

app/views/layouts/_menu.html.erb
<div id="menu">
  <div></div>
  <div></div>
  <div></div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="site-name">
    <a href="/">
      <%= image_tag "site-logo.svg" %>
      <div>海龜湯</div>
    </a>
  </div>

  <div class="user-info">
    <ul>
      <% if current_user %>
        <li>嘿，<%= current_user.name %>！</li>
        <li><%= link_to "登出", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to_if current_user.soups, "我開的湯", my_soups_path %></li>
      <% else %>
        <li><%= link_to "註冊", new_user_registration_path %></li>
        <li><%= link_to "登入", user_session_path %></li>
      <% end %>
    </ul>
  </div>
  <div class="more">
    <ul>
      <li><%= link_to "看看湯規則 ☺️", rules_soups_path %></li>
      <li><%= link_to "開一鍋新湯 ☺️", new_soup_path %></li>
      <li><%= link_to "看看有啥湯 ☺️", soups_path %></li>
      <li><%= link_to "已完結的湯 ☺️", soups_path(state: "finished") %></li>
    </ul>
  </div>
  <div class="messenger">
    <ul>
      <li><%= link_to "聯絡我們 🙋", "https://www.facebook.com/messages/t/1941351752849342/", target: "_blank" %></li>
    </ul>
  </div>

  <%= render "layouts/footer" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>海龜湯。TurtleSoup</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="description" content="海龜湯即時聊天室，歡迎開湯或猜湯：）">
    <meta name="og:title" content="海龜湯。TurtleSoup">
    <meta name="og:type" content="website">
    <meta name="og:url" content="http://turtle-soup.alanyeh20001.com">
    <meta name="og:image" content="<%= image_url('cover-image.png') %>">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= render "layouts/google_analytics" %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <%= render "layouts/navbar" %>
    <div class="main-content">
      <%= yield %>
    </div>
    <div id="overlay"></div>
  </body>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js'></script>

  <%= yield :page_specific_javascript %>
</html>